force-app/main/default/objects/Shelter__c/Shelter__c.object-meta.xml
<CustomObject>
    <label>Shelter</label>
    <nameField>
        <label>Shelter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shelters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shelter__c/fields/Closed_From__c.field-meta.xml
<CustomField>
    <fullName>Closed_From__c</fullName>
    <label>Closed From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Closed_To__c.field-meta.xml
<CustomField>
    <fullName>Closed_To__c</fullName>
    <label>Closed To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Friday_Close__c.field-meta.xml
<CustomField>
    <fullName>Friday_Close__c</fullName>
    <label>Friday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Friday_Open__c.field-meta.xml
<CustomField>
    <fullName>Friday_Open__c</fullName>
    <label>Friday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Monday_Close__c.field-meta.xml
<CustomField>
    <fullName>Monday_Close__c</fullName>
    <label>Monday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Monday_Open__c.field-meta.xml
<CustomField>
    <fullName>Monday_Open__c</fullName>
    <label>Monday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Saturday_Close__c.field-meta.xml
<CustomField>
    <fullName>Saturday_Close__c</fullName>
    <label>Saturday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Saturday_Open__c.field-meta.xml
<CustomField>
    <fullName>Saturday_Open__c</fullName>
    <label>Saturday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Sunday_Close__c.field-meta.xml
<CustomField>
    <fullName>Sunday_Close__c</fullName>
    <label>Sunday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Sunday_Open__c.field-meta.xml
<CustomField>
    <fullName>Sunday_Open__c</fullName>
    <label>Sunday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Thursday_Close__c.field-meta.xml
<CustomField>
    <fullName>Thursday_Close__c</fullName>
    <label>Thursday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Thursday_Open__c.field-meta.xml
<CustomField>
    <fullName>Thursday_Open__c</fullName>
    <label>Thursday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Tuesday_Close__c.field-meta.xml
<CustomField>
    <fullName>Tuesday_Close__c</fullName>
    <label>Tuesday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Tuesday_Open__c.field-meta.xml
<CustomField>
    <fullName>Tuesday_Open__c</fullName>
    <label>Tuesday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Wednesday_Close__c.field-meta.xml
<CustomField>
    <fullName>Wednesday_Close__c</fullName>
    <label>Wednesday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Wednesday_Open__c.field-meta.xml
<CustomField>
    <fullName>Wednesday_Open__c</fullName>
    <label>Wednesday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/ShelterController.cls
public with sharing class ShelterController {
    @AuraEnabled(cacheable=true)
    public static List<Shelter__c> getShelters() {
        return [
            SELECT Id, Name,
                Monday_Open__c, Monday_Close__c,
                Tuesday_Open__c, Tuesday_Close__c,
                Wednesday_Open__c, Wednesday_Close__c,
                Thursday_Open__c, Thursday_Close__c,
                Friday_Open__c, Friday_Close__c,
                Saturday_Open__c, Saturday_Close__c,
                Sunday_Open__c, Sunday_Close__c,
                Closed_From__c, Closed_To__c
            FROM Shelter__c
            ORDER BY Name ASC
        ];
    }
}