force-app/main/default/objects/Animal__c/fields/Date_of_admission__c.field-meta.xml
<CustomField>
    <fullName>Date_of_admission__c</fullName>
    <label>Date of admission</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Photo_Preview__c.field-meta.xml
<CustomField>
    <fullName>Photo_Preview__c</fullName>
    <formula>IMAGE(Photo__c, &quot;Photo&quot;, 200, 200)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Photo Preview</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Quarantine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AnimalController.cls
public with sharing class AnimalController {
    @AuraEnabled(cacheable=true)
    public static List<Animal__c> getLostAnimalsByDate(Date admissionDate) {
        List<Animal__c> animals = [
            select Id, Name, Status__c, Date_of_Admission__c
            from Animal__c
            Where Status__c = 'Lost' and Date_of_Admission__c = :admissionDate
        ];
        return animals;
    }

    @AuraEnabled(cacheable=true)
    public static List<Animal__c> getAnimalWithPhotos() {
        List<Animal__c> animals = [
            select Id, Name, Photo__c, Photo_Preview__c
            from Animal__c
            where Photo__c != null
        ];
        return animals;
    }
}